frontend/client/dark_chess_app/modules/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from dark_chess_app.modules.main import routes

frontend/client/dark_chess_app/modules/main/routes.py
from flask import render_template
from flask_login import current_user, login_required
from dark_chess_app.modules.main import main
from dark_chess_app.modules.auth.forms import LoginForm

@main.route('/')
@main.route('/index')
def index():
	if not current_user.is_authenticated:
		form = LoginForm()
		return render_template('main/index.html', form=form)
	return render_template('main/index.html')

@main.route('/about')
@login_required
def about():
	return render_template('main/about.html')

@main.route('/version-history')
@login_required
def version_history():
	return render_template('main/version_history.html')

frontend/client/dark_chess_app/templates/main/about.html
{% extends "shared/base.html" %}
{% block page_content %}
<h1 class="title">Darkchess</h1>
<a href="{{ url_for('main.version_history') }}">Version History</a>
{% endblock %}

frontend/client/dark_chess_app/templates/main/index.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import string_input, boolean_input %}
{% block page_content %}
<h1 class="title">Darkchess</h1>
{% if not current_user.is_authenticated %}
<h2 class="title form-title">Log In</h2>
<form action="{{url_for('auth.login')}}" method="post" novalidate="">
	{{ form.hidden_tag() }}
	{{ string_input(form.username, 'username', autofocus=True) }}
	{{ string_input(form.password, 'password') }}
	{{ boolean_input(form.remember_me, label=True) }}
	<button class="button button-navigation">Log In</button>
</form>
<a href="{{ url_for('main.index') }}" class="button button-navigation">Forgot Password?</a>
<a href="{{ url_for('auth.register') }}" class="button button-navigation">Sign Up</a>
{% endif %}
{% endblock %}

frontend/client/dark_chess_app/templates/main/version_history.html
{% extends "shared/base.html" %}
{% block css %}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/main/version_history.css') }}">
{% endblock %}
{% block page_content %}
<h1 class="title">Version History</h1>
<div class="header">
	<p>The first number in the numbering system, is the year, the second number is for the introduction of new (generally major) features, the third number is for small changes and bugfixes. Earlier versions also have either an 'a' or a 'cb', or 'ob', for 'Alpha', 'Closed Beta' and 'Open Beta' respectively. The date next to each version marks the last time a change was made under that version number.</p>
</div>
<article>
	{#
	<section>
		<h2>2020.1.0a (current)</h2>
		<div class="version-subsection">
			<h3>New Features</h3>
		</div>
		<div class="version-subsection">
			<h3>Changes</h3>
		</div>
		<div class="version-subsection">
			<h3>Bugfixes</h3>
		</div>
	</section>
	#}
	<section>
		<h2 class="section-title">2021.2.0a (current): 2021-02-19</h2>
		<div class="version-subsection">
			<h3 class="subsection-title">New Features</h3>
			<ul>
				<li>(client) The board has undergone significant visual changes (for the better) and been completely refactored to use the third-party js canvas library <a class="outside-link" href="https://konvajs.org/">konva.js</a>. This change allows increased development speed on the visual and interaction aspects of the board.</li>
			</ul>
			<img width="300" src="{{ url_for('static', filename='images/version_history/2021_2_0a/oldboard.png') }}" title="board before" alt="An image of the chessboard before visual changes."><img width="300" src="{{ url_for('static', filename='images/version_history/2021_2_0a/newboard.png') }}" title="board after" alt="An image of the chessboard after visual changes. there's added colors and sharpness">
		</div>
	</section>
	<section>
		<h2 class="section-title">2020.1.0a: 2020-12-18</h2>
		<div class="version-subsection">
			<h3 class="subsection-title">New Features</h3>
			<ul>
				<li>(api) Matches are now created through invites.</li>
			</ul>
		</div>
	</section>
</article>
{% endblock %}