backend/api/dark_chess_api/modules/docs/__init__.py
from flask import Blueprint

docs = Blueprint('docs', __name__)

from dark_chess_api.modules.docs import routes

backend/api/dark_chess_api/modules/docs/routes.py
from flask import current_app, render_template, abort
from dark_chess_api.modules.docs import docs

@docs.route('/')
@docs.route('/index')
def index():
	resources = current_app.endpoint_schemas.keys()
	return render_template('docs/index.html',
		resources=resources
	)

@docs.route('/<string:resource>/endpoints')
def doc_page(resource):
	if resource not in current_app.endpoint_schemas:
		abort(404)
	resources = current_app.endpoint_schemas.keys()
	endpoint_schemas = current_app.endpoint_schemas[resource]
	return render_template('docs/endpoint_doc_page.html',
		resources=resources,
		current_resource=resource,
		endpoint_schemas=endpoint_schemas
	)

backend/api/dark_chess_api/templates/docs/endpoint_doc_page.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Documentation Page - {{ resource }}</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/endpoints.css') }}">
		<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
	</head>
	<body>
		<div id="page-content">
			<header>
				<nav>
					<a href="{{ url_for('docs.index') }}">/index</a>
					{% for resource in resources %}
						{% if resource != current_resource %}
					<a href="{{ url_for('docs.doc_page', resource=resource) }}">/{{ resource }}</a>
						{% endif %}
					{% endfor %}
				</nav>
			</header>
			<div id="page-navigation">
				<ul>
					{% for schema in endpoint_schemas %}
					<li class="nav-link"><a href="#{{schema}}" data-nav-target="{{schema}}">{{ schema | replace('_', ' ') | title }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<div id="schemas">
				{% for schema_title, schema in endpoint_schemas.items() %}
				<div id="{{ schema_title }}" class="schema">
					<div class="schema-header">
						<div class="method method-{{schema.request_method | lower}}">
							<span>{{ schema.request_method }}</span>
						</div>
						<!-- <h2>{{ schema.title }}</h2> -->
						<h3 class="endpoint code">{{ schema.endpoint }}</h3>
					</div>
					<div class="schema-body hidden">
						<div class="title-and-description">
							<h3 class="schema-title">{{ schema.title }}</h3>
							<p class="schema-description">{{ schema.description }}</p>
						</div>
						{% if schema.additional_headers %}
						<div class="headers">
							<h4 class="subtitle">Headers</h4>
							<ul class="list-block">
								{% for header in schema.additional_headers %}
								<li class="header code">{{ header }}</li>
								{% endfor %}
							</ul>
						</div>
						{% endif %}
						{% if schema.type == 'object' %}
						<div class="parameters">
							<h4 class="subtitle">JSON Parameters</h4>
							<ul class="list-block">
								{% for param_title, param in schema.properties.items() %}
								<li class="param code">
									<div>
										<span>{{ param_title }}</span>
										<span>({{ param.type }})</span>
										{% if param_title in schema.required %}
										<span class="required">required</span>
										{% endif %}
									</div>
									<p class="param-description">{{ param.description }}</p>
								</li>
								{% endfor %}
							</ul>
						</div>
						{% endif %}
						<div id="{{ schema_title }}-responses" class="responses">
							<h4 class="subtitle">Responses</h4>
							<div class="tab-headers">
								{% for response in schema.responses %}
								<div class="tab-header {% if loop.first %}selected{% endif %}" data-schema-id="{{ schema_title }}-responses" data-response-code="{{ response.code }}">{{ response.code }}</div>
								{% endfor %}
							</div>
							{% for response in schema.responses %}
							{{ response_tab_content(loop.first, schema_title, response.code, response.example_json) }}
							{% endfor %}
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	<script src="{{ url_for('static', filename='javascript/prism.js') }}"></script>
	<script src="{{ url_for('static', filename='javascript/endpoints.js') }}"></script>
	</body>
</html>

backend/api/dark_chess_api/templates/docs/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Documentation Index</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
		<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
	</head>
	<body>
		<h3>Documentation pages:</h3>
		<ul id="resource-links">
			{% for resource in resources %}
			<li><a href="{{url_for('docs.doc_page', resource=resource)}}">{{ resource }}</a></li>
			{% endfor %}
		</ul>
		<h4>Notes regarding documentation</h4>
		<p>Some routes will document certain response codes as return a JSON response, even though they do not. For example, <span class="text-mixed-code">/user/auth/token</span> lists <span class="text-mixed-code">401</span> as returning <span class="text-mixed-code">{ error: "Unauthorized" }</span>, when in reality it returns a simple, unformatted unauthorized. This is because <span class="text-mixed-code">401</span>, as well as other responses are overloaded, and the documentation generator makes use of certain default values for these common responses.</p>
		<p>Rest assured that any response warranting (of course this is the opinion of the developer) further inspection beyond the status code will have accurate example JSON.</p>
	</body>
</html>