frontend/client/dark_chess_app/modules/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired

class UserSearchForm(FlaskForm):

	username = StringField('username', validators=[InputRequired()])

frontend/client/dark_chess_app/modules/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from dark_chess_app.modules.user import routes

frontend/client/dark_chess_app/modules/user/routes.py
import requests

from flask import render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required

from dark_chess_app.modules.user import user
from dark_chess_app.modules.user.forms import UserSearchForm
from dark_chess_app.utilities.api_utilities import authorized_api_request

@user.route('/profile')
@login_required
def current_user_profile():
	user_res = authorized_api_request(f'/user/{current_user.id}')
	if user_res.status_code != 200:
		abort(user_res.status_code)
	user_data = user_res.json()
	return render_template('user/current_user_profile.html',
		title=user_data['username'],
		user=user_data
	)

@user.route('/<int:id>/profile')
@login_required
def user_profile(id):
	user_res = authorized_api_request(f'/user/{id}')
	if user_res.status_code != 200:
		abort(user_res.status_code)
	user_data = user_res.json()
	is_friend = current_user.id in [f.id for f in user_data['friends']]
	return render_template('user/user_profile.html',
		title=user_data['username'],
		user=user_data,
		is_friend=is_friend,
		is_user=(user_data['id']==current_user.id)
	)

@user.route('/search', methods=['GET', 'POST'])
@login_required
def user_search():
	form = UserSearchForm()
	results = None
	if form.validate_on_submit():
		search_request = authorized_api_request('/user/search',
			method=requests.post,
			json={ 'username': form.username.data }
		)
		if search_request.status_code != 200:
			flash('Unable to load search results', 'error')
			return redirect(url_for('main.index'))
		results = search_request.json()
	return render_template('user/user_search.html',
		title='Search Results',
		form=form,
		results=results
	)

@user.route('/<int:id>/invite-friend')
@login_required
def invite_friend():
	

@user.route('/<int:id>/accept-friend-invite')
def accept_friend_invite():

frontend/client/dark_chess_app/templates/user/current_user_profile.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import user_link %}
{% block page_content %}
<h2>{{ user.username | e }}</h2>
<h4>Friends:</h4>
{% if user.friends %}
<li>
	{% for friend in user.friends %}
	{{ user_link(friend) }}
	{% endfor %}
</li>
{% else %}
<p>None yet</p>
{% endif %}
<div class="card stat-block">
	<ul>
		{% for stat, value in user.stats['games'] %}
		<li>{{stat}}: {{ value }}</li>
		{% endfor %}
	</ul>
	<p>Rating: {{ user.stats['rating'] }}</p>
</div>
{% endblock %}

frontend/client/dark_chess_app/templates/user/user_profile.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import user_link %}
{% block page_content %}
<h2>{{ user.username | e }}</h2>
{% if not is_friend and not is_user %}
<button data-user-id="{{ user.id }}">Invite Friend</button>
{% endif %}
<div class="card stat-block">
	<ul>
		{% for stat, value in user.stats.games.items() %}
		<li>{{ stat }}: {{ value }}</li>
		{% endfor %}
	</ul>
	<p>Rating: {{ user.stats.rating }}</p>
</div>
<div>
	{% if user.friends  %}
	<ul>
		{% for friend in user.friends %}
		<li>{{ user_link(friend) }}: <a href="{{ url_for('match.create_match', invited_id=friend.id) }}">create match</a></li>
		{% endfor %}
	</ul>
	{% else %}
	<p><a href="{{ url_for('user.user_search') }}">Search for some friends!</a></p>
	{% endif %}
</div>
{% endblock %}

frontend/client/dark_chess_app/templates/user/user_search.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import user_link, string_input %}
{% block page_content %}
<h2 class="title">User Search</h2>
<form action="" method="post" novalidate="">
	{{ form.hidden_tag() }}
	{{ string_input(form.username, 'username', autofocus=True) }}
	<button class="button">Search</button>
</form>
{% if results %}
<h3 class="subtitle">Results:</h3>
<ul>
	{% for user in results %}
	<li>{{ user_link(user) }}</li>
	{% endfor %}
</ul>
{% endif %}
{% endblock %}