frontend/client/dark_chess_app/modules/match/__init__.py
from flask import Blueprint

match = Blueprint('match', __name__)

from dark_chess_app.modules.match import routes, endpoints

frontend/client/dark_chess_app/modules/match/routes.py
import requests
from flask import render_template, redirect, url_for, jsonify, request, flash
from flask_login import current_user, login_required
from dark_chess_app.modules.match import match
from dark_chess_app.utilities.api_utilities import (
	api_request, authorized_api_request
)

@match.route('/create')
@login_required
def create_match():
	invited_id = request.args.get('invited_id', None)
	json = { 'invited_id': invited_id } if invited_id is not None else None
	create_match_res = authorized_api_request('/match/invite/create',
		requests.post,
		json=json
	)
	if create_match.status_code == 200:
		# invite_json = create_match_res.json()['match_invite']
		# redirect to match lobby
		flash('Created match.')
	elif create_match_res.status_code == 404:
		flash('No such opponent found, Unable to create match.')
	return redirect(url_for('main.index'))

@match.route('/invite/<int:id>/accept')
@login_required
def accept_match_invite(id):
	accept_invite_res = authorized_api_request(
		f'/match/invite/{id}/accept', requests.patch
	)
	if accept_invite_res.status_code == 200:
		match_json = accept_invite_res.json()['match']
		return redirect(url_for('match.match_page', id=match_json['id']))
	elif accept_invite_res.status_code == 403:
		flash('This match invite wasn\'t for you.', 'error')
	elif accept_invite_res.status_code == 410:
		flash('This match invite has already been accepted.', 'error')
	elif accept_invite_res.status_code == 404:
		flash('There\'s no such match invite.', 'error')
	else:
		flash('Unable to accept match invite.', 'error')
	return redirect(url_for('main.index'))

# Kept for when spectating becomes a thing

# @match.route('/<int:id>/join')
# @login_required
# def join_match(id):
# 	join_res = authorized_api_request(f'/match/{id}/join', requests.patch)
# 	# TODO handle errors
# 	return redirect(url_for('match.match_page', id=id))

@match.route('/open-matches')
@login_required
def open_matches():
	open_matches_res = authorized_api_request(f'/match/invite/query', requests.post,
		json={
			'is_open': True,
			'accepted': False
		}
	)
	open_matches = [
		m for m in open_matches_res.json()
		if m['inviter']['id'] != current_user.id
	]
	return render_template('match/open_match_invite_list.html',
		title='Match List',
		open_matches=open_matches
	)

# @match.route('/my-unnaccepted-invites')
# @login_required
# def users_unnaccepted_invites():
# 	invites_res = authorized_api_request('/match/invites/query', requests.post,
# 		json={
# 			'user_id': current_user.id,
# 			'accepted': False
# 		}
# 	)
# 	# TODO: Handle errors
# 	return render_template('match/active_match_invite_list.html',
# 		title='My Active Invites',
# 		invites=invites_res.json()
# 	)

@match.route('/my-match-invites')
@login_required
def users_match_invites():
	invites_res = authorized_api_request('/match/invite/query', requests.post,
		json={
			'involved_id': current_user.id,
			'accepted': False
		}
	)
	# TODO: Handle errors
	users_invites = []
	user_invited = []
	for invite in invites_res.json():
		if invite['inviter']['id'] == current_user.id:
			users_invites.append(invite)
		else:
			user_invited.append(invite)
	return render_template('match/users_match_invites.html',
		title='My Match Invites',
		users_invites=users_invites,
		user_invited=user_invited
	)

@match.route('/my-active-matches')
@login_required
def users_active_matches():
	matches_res = authorized_api_request(f'/match/query', requests.post,
		json={
			'user_id': current_user.id,
			'in_progress': True,
		}
	)
	# TODO: Handle errors
	return render_template('match/active_match_list.html',
		title='My Active Matches',
		matches=matches_res.json()
	)

@match.route('/<int:id>')
def match_page(id):
	match_res = authorized_api_request(f'/match/{id}')
	if match_res.status_code == 404:
		flash('No such match')
		return redirect(url_for('match.open_matches'))
	match_json = match_res.json()
	player_color = None
	if match_json['player_black'] and match_json['player_black']['id'] == current_user.id:
		player_color = 'black'
	elif match_json['player_white'] and match_json['player_white']['id'] == current_user.id:
		player_color = 'white'
	return render_template('match/match.html',
		title=match_json['id'],
		match=match_json,
		player_color=player_color
	)

@match.route('/<int:id>/history')
def match_history(id):
	match_res = authorized_api_request(f'/match/{id}')
	if match_res.status_code == 404:
		flash('No such match')
		return redirect(url_for('match.open_matches'))
	match_json = match_res.json()
	history = []
	if 'white_vision_history' in match_json:
		history = match_json['white_vision_history']
	elif 'black_vision_history' in match_json:
		history = match_json['black_vision_history']
	elif 'transparent_history' in match_json:
		history = match_json['transparent_history']
	expanded_history = []
	for fen in history:
		expanded_history.append([row for row in fen.split('/')])
	return render_template('match/history.html',
		title=f'{match_json["id"]} history',
		history=expanded_history,
		match=match_json
	)

frontend/client/dark_chess_app/templates/match/active_match_list.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import match_card with context %}
{% block page_content %}
<div class="page-action-bar">
	<a class="button button-navigation" href="{{ url_for('match.create_match') }}">Create</a>
</div>
<ul class="match-list wrap-list">
	{% for match_data in matches -%}
	{{ match_card(match_data) }}
	{%- endfor %}
</ul>
{% endblock %}

frontend/client/dark_chess_app/templates/match/history.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import board %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/match/board.css') }}">
{% endblock %}
{% block page_content %}
{% if history %}
<ol>
	{% for move in history %}
	<li>{{ move }}</li>
	{% endfor %}
</ol>
{% else %}
<h2>No moves seem to have been made yet in this match. Come back later.</h2>
{% endif %}
{% endblock %}

frontend/client/dark_chess_app/templates/match/match.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import user_link %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/match/board.css') }}">
{% endblock %}
{% block page_content %}
	<a href="{{ url_for('match.match_history', id=match.id) }}">history</a>
	<h2>Match: {{ match.id }}</h2>
	<button id="flip-board-button">⇅</button>
	<div id="player-black" class="player-container">
		{% if match.player_black %}
		<h3 id="player-{{ match.player_black.id }}" class="player-title player-black-title">{{ match.player_black.username }}</h3><i class="far fa-chevron-double-left"></i>
		{{ user_link(match.player_black) }}
		{% endif %}
	</div>
	<!-- <canvas id="board-canvas"></canvas> -->
	<div id="board"></div>
	<div id="player-white" class="player-container">
		{% if match.player_white %}
		<h3 id="player-{{ match.player_white.id }}" class="player-title player-white-title">{{ match.player_white.username }}</h3><i class="far fa-chevron-double-left"></i>
		{{ user_link(match.player_white) }}
		{% endif %}
	</div>
{% endblock %}
{% block js %}
<div id="match-data" data-match-data='{{ match | tojson }}' hidden></div>
<div id="player-data" data-player-data='{{ current_user.as_dict() | tojson }}' hidden></div>
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.5/socket.io.js"></script>#}
<script src="{{ url_for('static', filename='javascript/libs/socket.io.js')}}"></script>
<script src="{{ url_for('static', filename='javascript/libs/konva.js')}}"></script>
<script src="{{ url_for('static', filename='javascript/match/match.js', v=1) }}"></script>
{% endblock %}

frontend/client/dark_chess_app/templates/match/match_history.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import board %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/match/board.css') }}">
{% endblock %}
{% block page_content %}
<canvas id="board-canvas"></canvas>
{% endblock %}
{% block js %}
<div id="match-data" data-match-data='{{ match | tojson }}' hidden></div>
<script src="{{ url_for('static', filename='javascript/match/matchHistory.js') }}"></script>
{% endblock %}

frontend/client/dark_chess_app/templates/match/match_list.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import match_card with context %}
{% block page_content %}
<div class="page-action-bar">
	<a class="button button-navigation" href="{{ url_for('match.create_match') }}">Create</a>	
</div>
<ul class="match-list wrap-list">
	{% for match_data in matches -%}
	{{ match_card(match_data) }}
	{%- endfor %}
</ul>
{% endblock %}

frontend/client/dark_chess_app/templates/match/open_match_invite_list.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import match_invite_card with context %}
{% block page_content %}
<div class="page-action-bar">
	<a class="button button-navigation" href="{{ url_for('match.create_match') }}">Create</a>
</div>
{% if open_matches %}
<ul class="card-list match-invite-list wrap-list">
	{% for invite in open_matches -%}
	{{ match_invite_card(invite) }}
	{% endfor -%}
</ul>
{% else %}
<p>It doesn't look like there are any matches yet, why not create one?</p>
{% endif %}
{% endblock %}

frontend/client/dark_chess_app/templates/match/users_match_invites.html
{% extends "shared/base.html" %}
{% from "shared/macros.jinja" import match_invite_card with context %}
{% block page_content %}
<div class="page-action-bar">
	<a class="button button-navigation" href="{{ url_for('match.create_match') }}">Create</a>
</div>
<h3 class="title">Your Invites</h3>
{% if user_invited %}
<ul class="card-list match-invite-list wrap-list">
	{% for invite in user_invited -%}
	{{ match_invite_card(invite) }}
	{% endfor -%}
</ul>
{% else %}
<p>It looks live you don't have any invites right now.</p>
{% endif %}
<h3 class="title">Your Invites To Others</h3>
{% if users_invites %}
<ul class="card-list match-invite-list wrap-list">
	{% for invite in users_invites -%}
	{{ match_invite_card(invite) }}
	{% endfor -%}
</ul>
{% else %}
<p>It looks like you haven't invited anyone to a match right now.</p>
{% endif %}
{% endblock %}